export const educationPayload = [
  {
    year: 2023,
    title: 'Curso profesional de PHP',
    platform: 'Codigo Facilito',
    content: [
      'Variables y tipos',
      'Operadores',
      'Condiciones y ciclos',
      'Arreglos',
      'Funciones',
      'Programacion orientada a objetos',
      'Base de datos',
      'MVC',
    ],
    link: 'https://codigofacilito.com/cursos/php-profesional',
  },
  {
    year: 2023,
    title: 'Pruebas Unitarias con PHP',
    platform: 'Codigo Facilito',
    content: [
      'Asserts',
      'Creacion de helpers',
      'Setup y teardown',
      'Base de datos',
      'Pruebas con excepciones',
      'Salta tests',
      'SetupBeforeClass',
      'After y Before',
      'Generar reportes',
    ],
    link: 'https://codigofacilito.com/cursos/php-testing',
  },
  {
    year: 2022,
    title: 'Creacion de apis en laravel',
    platform: 'Platzi',
    content: [
      'Modelo y controlador',
      'Revetir migraciones y Guardar registros',
      'Traducir validaciones',
      'Mostrar, crear y eliminar registros',
      'Api resources',
      'Laravel Sanctum',
      'Test api',
      'Tablas relacionadas',
    ],
    link: 'https://platzi.com/cursos/laravel-api/',
  },
  {
    year: 2022,
    title: 'Fundamentos de Python',
    platform: 'Crehana',
    content: [
      'Conceptos basicos',
      'Estructuras de control',
      'Estructuras de datos',
      'Funciones',
    ],
    link: 'https://www.crehana.com/cursos-online-diseno-web/fundamentos-de-python/?source_page=Search%20Landing&source_detail=Search%20Landing&source=search&model_used=SEARCH_ENGINE_V2.2&product_name=Fundamentos%20de%20Python&product_id=12080&keyword=fundamentos%20de%20python&item_type=course&position_selected=0',
  },
];
